spring:
  application:
    name: kubik-commerce-store
  datasource:
    url: jdbc:h2:mem:storedb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /api/v01
  port: 8081